spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5332/recalldb
spring.datasource.username=danish
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=qoEHZ7oEBYpuD9RDlknqgsRilyekyuynBHf3rZVK7AO
jwt.expiration=3600000

file.upload-dir=E:/Projects/recall-app/recall/uploads
